name: unjabbed_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  art_sweetalert: ^0.0.5
  auto_size_text_field: ^2.1.0
  get: 4.6.5
  flutter: 
    sdk: flutter
  get_storage: ^2.0.3
  url_launcher: ^6.1.7
  intl: ^0.18.0
  cloud_firestore: ^4.3.1
  flutter_spinkit: ^5.1.0
  multi_select_flutter: ^4.1.3
  firebase_core: ^2.4.1

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/auth/
    - assets/
    - assets/translation/
    - assets/images/
  # fonts: 
  #   - family: Arial
  #     fonts: 
  #       - asset: asset/fonts/arial/ArialTh.ttf
  uses-material-design: true

